version: "2"

run:
  timeout: 3m
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - hugeParam
      - rangeValCopy
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: unreachable-code
      - name: redefines-builtin-id
  nakedret:
    max-func-lines: 30

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
